export default {
    tplCmpList: [{
        id: 1,
        name: 'c_text',
        icon: 'static/resource/img/cmp/text.png'
    }, {
        id: 2,
        name: 'c_image',
        icon: 'static/resource/img/cmp/image.png'
    }],
    tplCmpOptList: [{
        id: 1,
        tplCmpId: 1,
        name: '宽度',
        code: 'width',
        val: '1080px',
        type: 'number',
        kind: 'style',
        pos: 1
    }, {
        id: 2,
        tplCmpId: 1,
        name: '高度',
        code: 'height',
        val: '120px',
        type: 'number',
        kind: 'style',
        pos: 2
    }, {
        id: 3,
        tplCmpId: 2,
        name: '宽度',
        code: 'width',
        val: '1080px',
        type: 'number',
        kind: 'style',
        pos: 1
    }, {
        id: 4,
        tplCmpId: 2,
        name: '高度',
        code: 'height',
        val: '120px',
        type: 'number',
        kind: 'style',
        pos: 2
    }, {
        id: 5,
        tplCmpId: 1,
        name: '文本',
        code: 'text',
        val: '',
        type: 'text',
        kind: 'attr',
        pos: 1
    }, {
        id: 6,
        tplCmpId: 2,
        name: '地址',
        code: 'url',
        val: 'static/resource/img/cmp/image.png',
        type: 'mime',
        kind: 'attr',
        pos: 1
    }],
    insCmpList: [{
        id: 1,
        name: 'c_text'
    }, {
        id: 2,
        name: 'c_image'
    }, {
        id: 3,
        name: 'c_text'
    }],
    insCmpOptList: [{
        id: 1,
        tplCmpId: 1,
        name: '宽度',
        code: 'width',
        val: '1080px',
        type: 'number',
        kind: 'style',
        pos: 1
    }, {
        id: 2,
        tplCmpId: 1,
        name: '高度',
        code: 'height',
        val: '180px',
        type: 'number',
        kind: 'style',
        pos: 2
    }, {
        id: 3,
        tplCmpId: 2,
        name: '宽度',
        code: 'width',
        val: '1080px',
        type: 'number',
        kind: 'style',
        pos: 1
    }, {
        id: 4,
        tplCmpId: 2,
        name: '高度',
        code: 'height',
        val: '240px',
        type: 'number',
        kind: 'style',
        pos: 2
    }, {
        id: 5,
        tplCmpId: 3,
        name: '宽度',
        code: 'width',
        val: '1080px',
        type: 'number',
        kind: 'style',
        pos: 1
    }, {
        id: 6,
        tplCmpId: 3,
        name: '高度',
        code: 'height',
        val: '300px',
        type: 'number',
        kind: 'style',
        pos: 2
    }]
};
